global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
#   format: common  # common, json, logfmt
#   filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
# accesslog:
  # format: common  # common, json, logfmt
  # filePath: /var/log/traefik/access.log

# (Optional) Enable API and Dashboard
# ---
api:
 dashboard: true  # true by default
#  insecure: false  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443  

# Certificates configuration
# ---
# TODO: Custmoize your Cert Resolvers and Domain settings
# 
certificatesResolvers:
# LET'S ENCRYPT:
# ---
# 
  staging:
    acme:
      email: email@email.com.br  # TODO: Change this to your email
      storage: /ssl-certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: email@email.com.br  # TODO: Change this to your email
      storage: /ssl-certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# TODO: ADD HERE YOUR TRAEFIK PILOT TOKEN
# pilot:
#   token: "token"
  
# Provider Configuration
# ---
# TODO: Customize your Provider Settings if needed
# 
providers:
# DOCKER:
# ---
#
  docker:
    exposedByDefault: false  # Default is true
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
  